version: '3'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - ./var/db/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=app
    ports:
      - 3306:3306

  elasticsearch:
    image: elasticsearch:7.2.1
    volumes:
      - ./var/db/elasticearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    expose:
      - 9300
